CREATE OR REPLACE PROCEDURE CSE532.CLEANUP_MERGEZIP ()
	LANGUAGE SQL MODIFIES SQL DATA
	BEGIN

		UPDATE CSE532.PROCESS_TRACK_TABLE SET zipcode_process = 0;
		DELETE FROM CSE532.MERGE_COMPONENT_TABLE;
		DELETE FROM CSE532.ZIP_MEMBER_TABLE;		
		
	END@
