INSERT INTO CSE532.FACILITY(FACILITYID, FACILITYNAME, DESCRIPTION, ADDRESS1, ADDRESS2, CITY, STATE, ZIPCODE, COUNTYCODE, COUNTY, GEOLOCATION)
SELECT o.FACILITYID,
       o.FACILITYNAME,
       o.DESCRIPTION,
       o.ADDRESS1,
       o.ADDRESS2,
       o.CITY,
       o.STATE,
       o.ZIPCODE,
       o.COUNTYCODE,
       o.COUNTY,
       DB2GSE.ST_POINT(o.LONGITUDE, o.LATITUDE, 1)
       FROM CSE532.FACILITYORIGINAL o
;
