CREATE OR REPLACE PROCEDURE MERGE_ZIPCODE (OUT STDDEV NUMERIC(15,5))
	LANGUAGE SQL MODIFIES SQL DATA
	P1: BEGIN

		DECLARE NOTABLE CONDITION FOR SQLSTATE '42704'; 
    	

		DECLARE curr_avg_population DOUBLE DEFAULT 0;


  		DECLARE CONTINUE HANDLER FOR NOTABLE SET STDDEV = 3.0;

		SELECT CAST(SUM(z.ZPOP) AS double)/COUNT(*) INTO curr_avg_population
FROM CSE532.USZIP usz INNER JOIN
    CSE532.ZIPPOP z
    ON CAST(usz.ZCTA5CE10 AS INT) = z.ZIP;


        DROP TABLE CSE532.MERGE_ZIPCODE_SHAPES;    	

        CREATE TABLE CSE532.MERGE_ZIPCODE_SHAPES (
		    member_id INT,
		    zip_code INT,
		    zip_code_root INT,
		    shape DB2GSE.ST_MULTIPOLYGON
		);

	END P1@

CALL MERGE_ZIPCODE(?)@