CREATE OR REPLACE PROCEDURE MERGE_ZIPCODE (OUT STDDEV NUMERIC(15,5))
	LANGUAGE SQL MODIFIES SQL DATA
	P1: BEGIN

		DECLARE curr_avg_population DOUBLE DEFAULT 0;
		SELECT CAST(SUM(z.ZPOP) AS double)/COUNT(*) INTO curr_avg_population
FROM CSE532.USZIP usz INNER JOIN
    CSE532.ZIPPOP z
    ON CAST(usz.ZCTA5CE10 AS INT) = z.ZIP;


    	-- DECLARE NO_TABLE CONDITION FOR SQLSTATE '42704';
    	-- DROP TABLE CSE532.MERGE_ZIPCODE_SHAPES;

    	-- DECLARE CONTINUE HANDLER FOR NO_TABLE
    	-- SET STDDEV = curr_avg_population;

	END P1@

CALL MERGE_ZIPCODE(?)@